Nav/25/creating dashboard
nology-tech/quadra-client-project pull request #15
Opened 2022-11-02 10:04 UTC by ChrisWakley

Created Nav component and styling.

https://trello.com/c/fdFtRpUi/25-create-a-nav-folder-for-dashboard

2022-11-02 10:16 UTC, Zain-Ashfaq submitted a review, later dismissed
all good

2022-11-02 14:10 UTC, Martinelli-89 requested changes
Align text to icon.
Add transfer

2022-11-02 15:52 UTC, kirsty-nology requested changes
All css files should be removed and consistent use of rem and variables used in sass files please

2022-11-02 15:52 UTC, kirsty-nology commented on src/components/Layout/Layout.css
> +.layout {
remove all css files

2022-11-02 15:52 UTC, kirsty-nology commented on src/pages/Nav/Nav.jsx
> +        <h2 className="nav__menu-header">Menu</h2>
`className=nav__header`

2022-11-02 15:52 UTC, kirsty-nology commented on src/pages/Nav/Nav.scss
> +
remove extra lines

2022-11-03 10:18 UTC, kirsty-nology approved these changes

2022-11-03 10:45 UTC, kirsty-nology submitted a review, later dismissed

2022-11-03 10:47 UTC, Zain-Ashfaq approved these changes
class

2022-11-03 11:35 UTC, kirsty-nology approved these changes

2022-11-03 12:05 UTC, Martinelli-89 approved these changes

2022-11-03 12:05 UTC, merged