Created Contacts Component/31
nology-tech/quadra-client-project pull request #17
Opened 2022-11-02 10:44 UTC by Anushaca1995

Created .jsx and .scss files for contacts component and passed the appropriate props.

https://trello.com/c/zs8RfeFL/31-create-a-contact-component

2022-11-02 11:10 UTC, Martinelli-89 requested changes
- Missing background color
- Use rem instead of font sizes for font size
- Use rem for image sizes as well
- Delete button and bank imaged same size 

Thanks!

2022-11-02 15:36 UTC, kirsty-nology commented on src/components/Contacts/Contacts.scss
> +    &__Image{
lower case i for __image

2022-11-02 15:36 UTC, kirsty-nology commented on src/components/Contacts/Contacts.scss
> +    height: 3.63rem;
this too specific, do either 3.5 or 4

2022-11-02 15:38 UTC, kirsty-nology commented on src/components/Contacts/Contacts.jsx
> +            <img className="contacts__Image contacts__Image--bankImage" src={bankImage}></img>
lowercase i for `image`

2022-11-02 16:39 UTC, Zain-Ashfaq approved these changes
all works

2022-11-03 11:23 UTC, Martinelli-89 approved these changes

2022-11-03 11:39 UTC, kirsty-nology approved these changes

2022-11-03 11:40 UTC, merged