Searchbar/30 boilerplate
nology-tech/quadra-client-project pull request #18
Opened 2022-11-02 11:10 UTC by ChrisWakley

Created and styled Searchbar component boilerplate.

https://trello.com/c/wsiMQ0CS/30-create-a-search-bar-component

2022-11-02 12:41 UTC, Martinelli-89 requested changes
Only change the pixel for rem units, everything else is good

2022-11-02 15:47 UTC, kirsty-nology requested changes

2022-11-03 10:02 UTC, Zain-Ashfaq approved these changes
All good

2022-11-03 11:38 UTC, Martinelli-89 approved these changes

2022-11-03 12:10 UTC, kirsty-nology approved these changes

2022-11-03 12:12 UTC, Martinelli-89 approved these changes

2022-11-03 12:13 UTC, merged