added new icon and changed name
nology-tech/quadra-client-project pull request #37
Opened 2022-11-04 12:57 UTC by haoxle

added ice and new title

https://trello.com/c/E9XP9ehT/74-change-title-and-favicon-of-web-page

2022-11-04 15:16 UTC, LewisLovett commented
Favicon has not been changed

2022-11-04 16:52 UTC, AnnaKurochkina requested changes

2022-11-04 16:52 UTC, AnnaKurochkina commented on public/index.html
>        href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🎯</text></svg>"
change favicon from 🎯 to senergy favicon

2022-11-07 09:44 UTC, LewisLovett approved these changes

2022-11-07 09:47 UTC, AnnaKurochkina approved these changes

2022-11-07 09:47 UTC, merged