created a live rates page with some logic and styling
nology-tech/quadra-client-project pull request #39
Opened 2022-11-07 09:37 UTC by haoxle

Mock buttons have been added to implement logic,
components imported and styles altered to suit the page
basic styling added

https://trello.com/c/IMAeSaKO/70-create-live-rates-page

2022-11-07 11:23 UTC, LewisLovett requested changes
Resolve merge confilct

2022-11-07 12:57 UTC, olirob93 submitted a review, later dismissed
fine for approval once changes are made

2022-11-07 12:57 UTC, olirob93 commented on src/components/LiveRate/LiveRate.jsx
> +  image_url = "../assets/images/credit-card.png",
this file path won't work please can you import it in and use it instead

`import Flag from "../../assets/images/credit-card.png"`

`image_url = Flag`

2022-11-07 14:06 UTC, LewisLovett approved these changes

2022-11-07 14:18 UTC, AnnaKurochkina requested changes
Add LoggedIn component to the page please.

2022-11-07 14:18 UTC, kirsty-nology requested changes

2022-11-07 14:18 UTC, kirsty-nology commented on src/components/LiveRate/LiveRate.scss
> +  // width: 100vw;
remove comment

2022-11-07 14:18 UTC, kirsty-nology commented on src/pages/LiveRates/LiveRates.jsx
> +          <div></div>
why are there 3 empty `div`s here?

2022-11-07 14:18 UTC, kirsty-nology commented on src/pages/LiveRates/LiveRates.jsx
> +      <div className="rates-info">
`className=rates__info`

2022-11-07 14:18 UTC, kirsty-nology commented on src/pages/LiveRates/LiveRates.jsx
> +        <h1 className="rates-info__transfer"> Transfer </h1>
`className=rates__transfer`

2022-11-07 14:18 UTC, kirsty-nology commented on src/pages/LiveRates/LiveRates.jsx
> +        <h1 className="rates-info__heading"> View Latest Rates </h1>
`className=rates__heading`

2022-11-07 14:18 UTC, kirsty-nology commented on src/pages/LiveRates/LiveRates.jsx
> +        <p className="rates-info__content">
`className=rates__content`

2022-11-07 14:18 UTC, kirsty-nology commented on src/pages/LiveRates/LiveRates.jsx
> +      <div className="rates-ctner">
`className=rates__container`

2022-11-07 14:18 UTC, kirsty-nology commented on src/pages/LiveRates/LiveRates.jsx
> +        <div className="rates-ctner__title">
`className=rates__title`

2022-11-07 14:18 UTC, kirsty-nology commented on src/pages/LiveRates/LiveRates.jsx
> +            <h3 id="rates-ctner__title--head">Currency</h3>
`className=rates__title--head`

2022-11-07 14:18 UTC, kirsty-nology commented on src/pages/LiveRates/LiveRates.jsx
> +  );
curious about the thinking behind this... coming to chat to u in a sec

2022-11-07 14:32 UTC, AnnaKurochkina submitted a review, later dismissed
Can't find a cureency button.
![CurrencyButton](https://user-images.githubusercontent.com/73474619/200335758-54931ca1-e3ce-45b5-8621-c7de4b6d2cdb.png)

2022-11-08 11:01 UTC, LewisLovett approved these changes

2022-11-08 11:12 UTC, kirsty-nology requested changes

2022-11-08 11:12 UTC, kirsty-nology commented on src/pages/LiveRates/LiveRates.jsx
> +            <h3 id="container__title--head">Currency</h3>
`className=container__header`

2022-11-08 11:37 UTC, kirsty-nology approved these changes

2022-11-08 11:37 UTC, LewisLovett approved these changes

2022-11-08 11:39 UTC, merged