Feature/login/73 firebase login
nology-tech/quadra-client-project pull request #41
Opened 2022-11-07 11:44 UTC by Martinelli-89

Added state to save user after login in App.jsx
Login let user know if email or password for login is incorrect
Removed value from InputBox props because not used

2022-11-07 14:31 UTC, kirsty-nology requested changes

2022-11-07 14:31 UTC, kirsty-nology commented on src/pages/Login/Login.jsx
>                  <p className="welcome__text">Welcome Back!</p>
`className=signIn__message`

2022-11-07 15:37 UTC, LewisLovett requested changes
Resolve file conflicts

2022-11-07 16:20 UTC, Martinelli-89 commented on src/App.jsx
> +  },[user])
We were checking if you paid attention to lines of code not needed ;)

2022-11-07 16:48 UTC, LewisLovett submitted a review, later dismissed

2022-11-08 11:50 UTC, kirsty-nology approved these changes

2022-11-08 11:52 UTC, LewisLovett approved these changes

2022-11-08 11:52 UTC, merged