features/Converter/45-convert-box
nology-tech/quadra-client-project pull request #42
Opened 2022-11-07 12:37 UTC by blueretrograde

-Changed the styling to a grid for more flexibility across different sizes/screens
-General styling to reflect the Figma designs

https://trello.com/c/tDTVqqmY/45-create-a-currency-conversion-component

2022-11-07 14:39 UTC, kirsty-nology requested changes

2022-11-07 14:39 UTC, kirsty-nology commented on .eslintrc.json
> +    "no-unused-vars": "off"
this needs to be removed

2022-11-07 14:39 UTC, kirsty-nology commented on src/components/currencyConverter/CurrencyConverter.jsx
> +
remove extra line

2022-11-07 14:39 UTC, kirsty-nology commented on src/components/currencyConverter/CurrencyConverter.jsx
> +        <h3 id="header__amount">Amount</h3>
`className=converter__amount`

2022-11-07 14:39 UTC, kirsty-nology commented on src/components/currencyConverter/CurrencyConverter.jsx
> +        <h3 id="header__to">To</h3>
`className=converter__to`

2022-11-07 14:39 UTC, kirsty-nology commented on src/components/currencyConverter/CurrencyConverter.jsx
> +            id="input__amount"
`className=converter__input`

2022-11-07 14:39 UTC, kirsty-nology commented on src/components/currencyConverter/CurrencyConverter.jsx
> +        <div className="input__from">
`className=converter__source`

2022-11-07 14:39 UTC, kirsty-nology commented on src/components/currencyConverter/CurrencyConverter.jsx
> +            <Dropdown  id="from" title={fromCurrency} icon={iconMap[fromCurrency]} onSelect={handleFromChange} value={fromCurrency}>
`className=converter__sourceInput`

2022-11-07 14:39 UTC, kirsty-nology commented on src/components/currencyConverter/CurrencyConverter.jsx
> +        <div className="convertBox__button">
`className=converter__submitWrapper`

2022-11-07 14:39 UTC, kirsty-nology commented on src/components/currencyConverter/CurrencyConverter.jsx
> +            <Button className="convert__button" buttonText={"Convert"}/>
`className=converter__submitButton`

2022-11-07 15:51 UTC, blueretrograde commented on .eslintrc.json
> +    "no-unused-vars": "off"
removed

2022-11-07 15:53 UTC, blueretrograde commented on src/components/currencyConverter/CurrencyConverter.jsx
> +
done

2022-11-07 15:54 UTC, blueretrograde commented on src/components/currencyConverter/CurrencyConverter.jsx
> +    <div className="convertBox">
done

2022-11-07 15:56 UTC, blueretrograde commented on src/components/currencyConverter/CurrencyConverter.jsx
> +        <h3 id="header__amount">Amount</h3>
done

2022-11-07 15:56 UTC, blueretrograde commented on src/components/currencyConverter/CurrencyConverter.jsx
> +        <h3 id="header__to">To</h3>
done

2022-11-07 15:57 UTC, blueretrograde commented on src/components/currencyConverter/CurrencyConverter.jsx
> +            id="input__amount"
done

2022-11-07 15:58 UTC, blueretrograde commented on src/components/currencyConverter/CurrencyConverter.jsx
> +        <div className="input__from">
done

2022-11-07 15:59 UTC, blueretrograde commented on src/components/currencyConverter/CurrencyConverter.jsx
> +            <Dropdown  id="from" title={fromCurrency} icon={iconMap[fromCurrency]} onSelect={handleFromChange} value={fromCurrency}>
done

2022-11-07 15:59 UTC, blueretrograde commented on src/components/currencyConverter/CurrencyConverter.jsx
> +        <div className="convertBox__btn">
done

2022-11-07 16:00 UTC, blueretrograde commented on src/components/currencyConverter/CurrencyConverter.jsx
> +            <img  id="convert" src={Convert} alt="" />
done

2022-11-07 16:00 UTC, blueretrograde commented on src/components/currencyConverter/CurrencyConverter.jsx
> +        <div className="input__to">
done

2022-11-07 16:01 UTC, blueretrograde commented on src/components/currencyConverter/CurrencyConverter.jsx
> +            <Dropdown  id="to" title={toCurrency} icon={iconMap[toCurrency]} onSelect={handleToChange}>
done

2022-11-07 16:02 UTC, blueretrograde commented on src/components/currencyConverter/CurrencyConverter.jsx
> +            <Button className="convert__button" buttonText={"Convert"}/>
done

2022-11-08 10:32 UTC, kirsty-nology approved these changes

2022-11-08 10:49 UTC, stu-slicer approved these changes

2022-11-08 10:53 UTC, merged