Fetures/button styling/62
nology-tech/quadra-client-project pull request #49
Opened 2022-11-08 14:53 UTC by ChrisWakley

Created and implimented various button styles via props to all buttons already used in the app.

https://trello.com/c/zqtVindJ/62-update-button-styling

2022-11-08 15:56 UTC, olirob93 approved these changes

2022-11-08 16:42 UTC, stu-slicer approved these changes

2022-11-09 09:15 UTC, olirob93 approved these changes

2022-11-09 09:21 UTC, stu-slicer submitted a review, later dismissed

2022-11-09 09:23 UTC, kirsty-nology requested changes

2022-11-09 09:23 UTC, kirsty-nology commented on src/pages/Login/Login.jsx
> +    validatEmail();
`validateEmail()`

2022-11-09 09:23 UTC, kirsty-nology commented on src/pages/Login/Login.jsx
> +  const validatEmail = () => {
`validateEmail`

2022-11-09 09:23 UTC, kirsty-nology commented on src/components/Button/Button.jsx
> +const Button = ({buttonText, handleClick, classNaming}) =>{
Is `classNaming` the best name for this prop? It is not a descriptive name specific to `button` - maybe `buttonClass` or `buttonStyle` would be better?

2022-11-09 09:34 UTC, kirsty-nology approved these changes

2022-11-09 09:41 UTC, stu-slicer approved these changes

2022-11-09 09:42 UTC, merged