Features/contacts-content/106-searchbar
nology-tech/quadra-client-project pull request #61
Opened 2022-11-10 15:36 UTC by blueretrograde

-added functionality to the searchbar component
-imported the searchbar component into Contact Content

https://trello.com/c/9VOMGb4Q/106-add-search-functionality-to-contact-list-page

2022-11-10 16:15 UTC, kirsty-nology requested changes

2022-11-10 16:15 UTC, kirsty-nology commented on src/components/ContactContent/ContactContent.jsx
> +
have only new line after declaring states

2022-11-10 16:15 UTC, kirsty-nology commented on src/components/ContactContent/ContactContent.jsx
remove blank line

2022-11-10 16:15 UTC, kirsty-nology commented on src/components/ContactContent/ContactContent.jsx
> +
remove extra line

2022-11-10 16:15 UTC, kirsty-nology commented on src/components/ContactContent/ContactContent.jsx
> +                <p className="contactList__desc">All your friends and family financial details in one place. Easily transfer currency internationally at the best possible rates.</p>
```
<p className="contactList__desc">
            All your friends and family financial details in one place. Easily transfer currency internationally at the best possible rates.
</p>
```

2022-11-10 16:15 UTC, kirsty-nology commented on src/components/ContactContent/ContactContent.jsx
> +
remove extra line

2022-11-10 16:15 UTC, kirsty-nology commented on src/components/ContactContent/ContactContent.scss
> +
remove extra line

2022-11-10 16:15 UTC, kirsty-nology commented on src/components/ContactContent/ContactContent.scss
> +    // margin-left: -8rem;
remove comment

2022-11-11 09:53 UTC, blueretrograde commented on src/components/ContactContent/ContactContent.scss
> +    // margin-left: -8rem;
all changes done

2022-11-11 10:05 UTC, ChrisWakley approved these changes
All changes actioned, merge conflict resolved.

2022-11-11 10:05 UTC, lanniiee approved these changes

2022-11-11 10:11 UTC, kirsty-nology approved these changes

2022-11-11 10:11 UTC, merged